#!/usr/bin/env bash

if [[ ! -e ${LKTOOLS_DIR}/oncotator || ! -z $FORCE_REINSTALL ]];
then
    echo "Cleaning up previous installs"
    rm -Rf STAR_2.4*
    rm -Rf $LKTOOLS_DIR/oncotator

    wget --read-timeout=10 https://github.com/broadinstitute/oncotator/archive/v1.8.0.0.tar.gz
    gunzip oncotator-1.8.0.0.tar.gz
    tar -xf oncotator-1.8.0.0.tar
    gzip oncotator-1.8.0.0.tar

    pip install virtualenv
    install ./scripts/create_oncotator_venv.sh -e $LKTOOLS_DIR/oncotator
else
    echo "Already installed"
fi